# Generated by Django 5.0.3 on 2024-03-23 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PuestoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=30)),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('cobro_año', models.BooleanField()),
                ('pago_extra', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_poblacion', models.CharField(max_length=200)),
                ('Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fabrica', models.CharField(max_length=100)),
                ('direccion2', models.CharField(max_length=100)),
                ('codigo_postal', models.IntegerField()),
                ('Poblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.poblacion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('puesto_trabajo', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=50)),
                ('name_fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.fabricas')),
                ('name_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.puestotrabajo')),
            ],
        ),
        migrations.AddField(
            model_name='puestotrabajo',
            name='salario_monto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.salarios'),
        ),
    ]
